### ISSUE TITLE
Variant filtering

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-jointgenotyping-workflow#6]
Talking to the Rios team, the variants they received from Hudson Alpha were fairly "raw" resulting in some discussion about variants that appeared to be de novo, but had little evidence in the BAMs. Would be good to verify what filtering was missing and how that fits into this workflow or downstream annotation/filtering.

**Comment by yuankunzhu** [comment]
@allisonheath move this issue to https://github.com/kids-first/kf-genomics-harmonization/ for better tracking

**Comment by yuankunzhu** [comment]
Issue moved to [kids-first/kf-genomics-harmonization #49](https://github.com/kids-first/kf-genomics-harmonization/issues/49) via [**ZenHub**](https://www.zenhub.com/)
